### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by DefCon-018** [kaustubhgupta/Hacktoberfest#287] opened 2020-10-08 13:12 UTC
Write an efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.

**Is your feature request related to a problem? Please describe.**
It is not a problem. It is an efficient algorithm to find largest subarray in sum in O(n) complexity

**Describe the solution you'd like**
Simple idea of the Kadane’s algorithm is to look for all positive contiguous segments of the array.

**Additional context**

**Languages**

-   [x] Python : @13snehitha
-   [x] Java : @DefCon-018
-   [x] C: @rgarg-2711
-   [x] C++: @Blackwidow2981

**Comment by 13snehitha** [comment] 2020-10-08 13:29
@kaustubhgupta Can you please allot this to me, i can do it in python.

**Comment by rgarg-2711** [comment] 2020-10-08 19:14
can you please assign it to me?

**Comment by Blackwidow2981** [comment] 2020-10-08 20:01
Hi ,
I would love to work on this project  in Java.

**Comment by kaustubhgupta** [comment] 2020-10-09 06:07
@Blackwidow2981 can you take this up in C++?

**Comment by motabhai-bhagwaan** [comment] 2020-10-09 06:22
Hi Kaustubh,

Can I work on this in C++, if the issue is still open?

**Comment by Blackwidow2981** [comment] 2020-10-09 07:36
yes @kaustubhgupta I can take it up in c++

**Comment by LalwaniSurendra** [comment] 2020-10-09 17:59
Can I take this in Java?

**Comment by sarthak-1503** [comment] 2020-10-10 13:15
I have added Kadane's Algorithm in C++ programming language. Please review my pull request.

**Comment by sarthak-1503** [comment] 2020-10-10 13:19
Please review my pull request #359

**Comment by kaustubhgupta** [comment] 2020-10-10 15:21
> Please review my pull request #359

Your PR was marked invalid as neither you were assigned this issue nor the assignment was needed as all languages are already assigned

**Comment by sarthak-1503** [comment] 2020-10-10 16:25
Sorry, I am a beginner in open source. Can you please assign it to me now for C++ if it's available?

**Closed as completed** 2020-10-12 04:38 UTC
Labels: good first issue, hacktoberfest, python, c++, java, C, assigned
